name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone lively4-core repository
      uses: actions/checkout@v2
    - name: Use Node.js 0.11
      uses: actions/setup-node@v1
      with:
        node-version: 0.11
    - name: Set up dependencies
      run: |
        # Use https (public access) instead of git for git-submodules
        sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
        git submodule update --init --recursive
    - name: Run 'npm test'
      run: npm test
