name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone lively4-core repository
      uses: actions/checkout@v2
    - name: Use Node.js 0.11
      uses: actions/setup-node@v1
      with:
        node-version: 0.11
    - name: Set up environment
      run: |
        sudo apt-get install -yq --no-install-recommends xvfb
        echo "CHROME_BIN=$(which google-chrome-stable)" >> $GITHUB_ENV
    - run: npm install
    - run: xvfb-run npm test
